# Generated by Django 5.2.6 on 2025-11-10 20:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBasicWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(choices=[(1, 'Unit 1 — Introduce yourself'), (2, 'Unit 2 — Greetings'), (3, 'Unit 3 — Order drinks'), (4, 'Unit 4 — Introduce family members'), (5, 'Unit 5 — Talk to the waiter'), (6, 'Unit 6 — Discuss places')])),
                ('english', models.CharField(max_length=100)),
                ('hindi', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson_basic/images/')),
                ('audio_en', models.FileField(blank=True, null=True, upload_to='lesson_basic/audio/')),
                ('audio_hi', models.FileField(blank=True, null=True, upload_to='lesson_basic/audio/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lesson Basic Word',
                'verbose_name_plural': 'Lesson Basic Words',
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('hindi', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='vocab_banners/')),
                ('video', models.FileField(blank=True, null=True, upload_to='vocab_videos/')),
                ('english_audio', models.FileField(blank=True, null=True, upload_to='vocab_audio/')),
                ('hindi_audio', models.FileField(blank=True, null=True, upload_to='vocab_audio/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to='lessons.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('quizzes_completed', models.PositiveIntegerField(default=0)),
                ('words_learned', models.PositiveIntegerField(default=0)),
                ('easy_words_learned', models.PositiveIntegerField(default=0)),
                ('medium_words_learned', models.PositiveIntegerField(default=0)),
                ('hard_words_learned', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('today_progress', models.FloatField(default=0.0)),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lessons.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='DailyXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('xp_gained', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=120, null=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.appuser')),
            ],
            options={
                'unique_together': {('app_user', 'date', 'reason')},
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned', models.BooleanField(default=False)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.vocabularyword')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
