# Generated by Django 5.2.6 on 2025-11-10 21:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonbasicword',
            options={'ordering': ['unit', 'order']},
        ),
        migrations.RemoveField(
            model_name='lessonbasicword',
            name='audio_en',
        ),
        migrations.RemoveField(
            model_name='lessonbasicword',
            name='audio_hi',
        ),
        migrations.AddField(
            model_name='lessonbasicword',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_words/audio/'),
        ),
        migrations.AlterField(
            model_name='lessonbasicword',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_words/'),
        ),
        migrations.AlterField(
            model_name='lessonbasicword',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lessonbasicword',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='LessonBasicCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_basic_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Basic Completion',
                'verbose_name_plural': 'Lesson Basic Completions',
                'unique_together': {('user', 'unit')},
            },
        ),
    ]
