# Generated by Django 5.2.6 on 2025-11-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessonbasicword_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonbasicword',
            name='audio',
        ),
        migrations.AddField(
            model_name='lessonbasicword',
            name='english_audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_words/audio/english/'),
        ),
        migrations.AddField(
            model_name='lessonbasicword',
            name='hindi_audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_words/audio/hindi/'),
        ),
    ]
