# Generated by Django 5.2.6 on 2025-11-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lessonbasicword_audio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonbasiccompletion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonbasiccompletion',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonbasiccompletion',
            name='lesson_name',
            field=models.CharField(default='Unit 1 - Basic', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonbasiccompletion',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='lessonbasiccompletion',
            name='unit',
        ),
    ]
