# Generated by Django 5.2.6 on 2025-11-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lessonbasiccompletion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonbasicword',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='lessonbasicword',
            old_name='english',
            new_name='english_word',
        ),
        migrations.RenameField(
            model_name='lessonbasicword',
            old_name='hindi',
            new_name='hindi_word',
        ),
        migrations.RemoveField(
            model_name='lessonbasicword',
            name='unit',
        ),
        migrations.AddField(
            model_name='lessonbasicword',
            name='lesson_name',
            field=models.CharField(default='Unit 1 - Basic', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonbasicword',
            name='english_audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_basic/audio/en/'),
        ),
        migrations.AlterField(
            model_name='lessonbasicword',
            name='hindi_audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_basic/audio/hi/'),
        ),
        migrations.AlterField(
            model_name='lessonbasicword',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_basic/images/'),
        ),
        migrations.AlterField(
            model_name='lessonbasicword',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
