# Generated by Django 5.2.6 on 2025-11-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lessonbasicword_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(default='Unit 1 - Quiz', max_length=100)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson_quiz/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='lesson_quiz/videos/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
