# Generated by Django 5.2.6 on 2025-11-10 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lessonquizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonquizquestion',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='lessonquizquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='LessonQuizCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Quiz Completion',
                'verbose_name_plural': 'Lesson Quiz Completions',
            },
        ),
    ]
